#include "Renderer.hpp"
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#ifdef __APPLE__
#include <OpenGL/gl3.h>
#else
#include <GL/gl.h>
#endif
#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <vector>
#include <cstdint>
namespace {std::string readText(const std::string&p){std::ifstream f(p);if(!f)return {};std::ostringstream s;s<<f.rdbuf();return s.str();}
bool shader(GLuint&out,GLenum type,const std::string&s,std::string&err){out=glCreateShader(type);const char*p=s.c_str();glShaderSource(out,1,&p,nullptr);glCompileShader(out);GLint ok=0;glGetShaderiv(out,GL_COMPILE_STATUS,&ok);if(!ok){GLint n=0;glGetShaderiv(out,GL_INFO_LOG_LENGTH,&n);std::string log(std::max(1,n),'\0');glGetShaderInfoLog(out,n,nullptr,log.data());err=log;glDeleteShader(out);out=0;return false;}return true;}
GLuint linkProgram(const std::string&vs,const std::string&fs,std::string&err){GLuint v=0,f=0;if(!shader(v,GL_VERTEX_SHADER,vs,err)||!shader(f,GL_FRAGMENT_SHADER,fs,err)){if(v)glDeleteShader(v);if(f)glDeleteShader(f);return 0;}GLuint p=glCreateProgram();glAttachShader(p,v);glAttachShader(p,f);glLinkProgram(p);glDeleteShader(v);glDeleteShader(f);GLint ok=0;glGetProgramiv(p,GL_LINK_STATUS,&ok);if(!ok){GLint n=0;glGetProgramiv(p,GL_INFO_LOG_LENGTH,&n);err.resize(std::max(1,n));glGetProgramInfoLog(p,n,nullptr,err.data());glDeleteProgram(p);return 0;}return p;}
void perspective(float*m,float fovy,float aspect,float zn,float zf){float f=1/std::tan(fovy*.5f);for(int i=0;i<16;i++)m[i]=0;m[0]=f/aspect;m[5]=f;m[10]=(zf+zn)/(zn-zf);m[11]=-1;m[14]=(2*zf*zn)/(zn-zf);}
void mul(float*o,const float*a,const float*b){float r[16]{};for(int c=0;c<4;c++)for(int rr=0;rr<4;rr++)for(int k=0;k<4;k++)r[c*4+rr]+=a[k*4+rr]*b[c*4+k];std::copy(r,r+16,o);}struct RawImage{int w=0,h=0;std::vector<unsigned char> rgba;};
bool readRawImage(const std::string&path,RawImage&img,std::string&err){std::ifstream f(path,std::ios::binary);if(!f){err="cannot read overlay texture "+path;return false;}uint32_t w=0,h=0;f.read(reinterpret_cast<char*>(&w),4);f.read(reinterpret_cast<char*>(&h),4);if(!f||w==0||h==0||w>32768||h>32768){err="invalid overlay texture header "+path;return false;}img.w=int(w);img.h=int(h);img.rgba.resize(size_t(w)*size_t(h)*4);f.read(reinterpret_cast<char*>(img.rgba.data()),std::streamsize(img.rgba.size()));if(!f){err="truncated overlay texture "+path;return false;}return true;}
bool makeTexture(const std::string&path,GLuint&tex,int&w,int&h,std::string&err){RawImage img;if(!readRawImage(path,img,err))return false;if(!tex)glGenTextures(1,&tex);glBindTexture(GL_TEXTURE_2D,tex);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA8,img.w,img.h,0,GL_RGBA,GL_UNSIGNED_BYTE,img.rgba.data());glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);w=img.w;h=img.h;return true;}
float smoother(float a,float b,float x){x=std::clamp((x-a)/(b-a),0.f,1.f);return x*x*(3.f-2.f*x);}}
bool Renderer::init(GLFWwindow*,const std::string&dir){std::string vs=readText(dir+"/wire.vert"),fs=readText(dir+"/wire.frag");if(vs.empty()||fs.empty()){error_="cannot read shaders from "+dir;return false;}program_=linkProgram(vs,fs,error_);if(!program_)return false;uMVP_=glGetUniformLocation(program_,"uMVP");uTime_=glGetUniformLocation(program_,"uTime");uColor_=glGetUniformLocation(program_,"uColor");uMusicLevel_=glGetUniformLocation(program_,"uMusicLevel");glGenVertexArrays(1,&vao_);glGenBuffers(1,&vbo_);glGenBuffers(1,&ebo_);glGenVertexArrays(1,&postVao_);if(!initPost(dir))return false;if(!initOverlay("assets/overlay"))return false;glEnable(GL_DEPTH_TEST);glDepthFunc(GL_LEQUAL);return true;}
bool Renderer::initPost(const std::string&dir){std::string vs=readText(dir+"/post.vert"),fs=readText(dir+"/post.frag");if(vs.empty()||fs.empty()){error_="cannot read post shaders from "+dir;return false;}postProgram_=linkProgram(vs,fs,error_);if(!postProgram_)return false;uPostScene_=glGetUniformLocation(postProgram_,"uScene");uPostTime_=glGetUniformLocation(postProgram_,"uTime");uPostResolution_=glGetUniformLocation(postProgram_,"uResolution");uPostMusic_=glGetUniformLocation(postProgram_,"uMusicLevel");glUseProgram(postProgram_);if(uPostScene_>=0)glUniform1i(uPostScene_,0);return true;}
bool Renderer::initOverlay(const std::string&dir){
 const std::string vs="#version 410 core\nlayout(location=0)in vec2 p;layout(location=1)in vec2 uv;out vec2 vUv;uniform float uTime;uniform float uFx;void main(){vec2 q=p;float wave=sin((uv.y+uTime*.34)*28.0)*.006*uFx;q.x+=wave;vUv=uv;gl_Position=vec4(q,0,1);}\n";
 const std::string fs="#version 410 core\nin vec2 vUv;out vec4 o;uniform sampler2D uTex;uniform sampler2D uScene;uniform float uAlpha;uniform vec3 uTint;uniform float uTime;uniform float uFx;float bolt(vec2 p,float seed){float y=.16*sin(p.x*(13.+seed*4.)+uTime*(4.5+seed))+.07*sin(p.x*(37.+seed*9.)-uTime*7.)+.12*sin(seed*8.);return exp(-abs(p.y-y)*(150.+uFx*80.))*smoothstep(1.1,.12,abs(p.x));}void main(){vec2 uv=vUv;float scan=.82+.18*sin((uv.y+uTime*.85)*900.0);float sweep=smoothstep(.055,.0,abs(fract(uv.x+uTime*.16)-.5));vec2 ca=vec2(.0025*uFx*(.5+.5*sin(uTime*5.0)),0);vec4 c=texture(uTex,uv);vec4 r=texture(uTex,uv+ca);vec4 b=texture(uTex,uv-ca);c.r=mix(c.r,r.r,.55*uFx);c.b=mix(c.b,b.b,.55*uFx);float around=max(max(texture(uTex,uv+vec2(.004,0)).a,texture(uTex,uv-vec2(.004,0)).a),max(texture(uTex,uv+vec2(0,.004)).a,texture(uTex,uv-vec2(0,.004)).a));float halo=clamp(around-c.a,0.,1.)*(1.-c.a);vec3 scene=texture(uScene,uv).rgb;float wireEnergy=clamp(dot(scene,vec3(.22,.38,.68))*.18,0.,1.);float flash=.72+.28*sin(uTime*5.5+wireEnergy*18.);float arc=bolt(uv*2.-1.,1.)+bolt((uv.yx*2.-1.)*vec2(1.,-1.),2.)+pow(max(0.,sin(uv.x*31.-uv.y*17.+uTime*10.+wireEnergy*9.)),24.)*.3;float lightning=halo*arc*uFx*(.75+wireEnergy*2.2);float a=min(1.,c.a*uAlpha+lightning*.8+halo*wireEnergy*.32);vec3 glow=(c.rgb*uTint)*(1.0+.65*sweep*uFx+wireEnergy*1.35+flash*.12);vec3 hot=vec3(1.0,.18,.06)*(pow(max(c.r-c.b,.0),1.7)*.85*uFx);vec3 energy=mix(vec3(.02,.45,1.3),vec3(1.2,.04,.01),step(c.b,c.r));o=vec4((glow+hot+energy*lightning*(1.8+wireEnergy*2.5))*scan,a);}\n";
 overlayProgram_=linkProgram(vs,fs,error_);if(!overlayProgram_)return false;
 glGenVertexArrays(1,&overlayVao_);glGenBuffers(1,&overlayVbo_);
 uOverlayTex_=glGetUniformLocation(overlayProgram_,"uTex");uOverlayScene_=glGetUniformLocation(overlayProgram_,"uScene");uOverlayAlpha_=glGetUniformLocation(overlayProgram_,"uAlpha");uOverlayTint_=glGetUniformLocation(overlayProgram_,"uTint");uOverlayTime_=glGetUniformLocation(overlayProgram_,"uTime");uOverlayFx_=glGetUniformLocation(overlayProgram_,"uFx");
 glUseProgram(overlayProgram_);if(uOverlayTex_>=0)glUniform1i(uOverlayTex_,0);if(uOverlayScene_>=0)glUniform1i(uOverlayScene_,1);
 bool ok=true;ok=ok&&makeTexture(dir+"/logo.rgba",logoTex_,logoW_,logoH_,error_);ok=ok&&makeTexture(dir+"/greets.rgba",greetsTex_,greetsW_,greetsH_,error_);ok=ok&&makeTexture(dir+"/accent.rgba",accentTex_,accentW_,accentH_,error_);ok=ok&&makeTexture(dir+"/scroller.rgba",scrollerTex_,scrollerW_,scrollerH_,error_);if(ok){glBindTexture(GL_TEXTURE_2D,scrollerTex_);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_REPEAT);}return ok;
}
bool Renderer::resizeHdr(int width,int height){width=std::max(1,width);height=std::max(1,height);if(width==hdrW_&&height==hdrH_&&hdrFbo_)return true;hdrW_=width;hdrH_=height;if(!hdrFbo_)glGenFramebuffers(1,&hdrFbo_);if(!hdrTex_)glGenTextures(1,&hdrTex_);if(!depthRbo_)glGenRenderbuffers(1,&depthRbo_);glBindTexture(GL_TEXTURE_2D,hdrTex_);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA16F,width,height,0,GL_RGBA,GL_FLOAT,nullptr);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);glBindRenderbuffer(GL_RENDERBUFFER,depthRbo_);glRenderbufferStorage(GL_RENDERBUFFER,GL_DEPTH_COMPONENT24,width,height);glBindFramebuffer(GL_FRAMEBUFFER,hdrFbo_);glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,hdrTex_,0);glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_DEPTH_ATTACHMENT,GL_RENDERBUFFER,depthRbo_);if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE){error_="HDR framebuffer incomplete";glBindFramebuffer(GL_FRAMEBUFFER,0);return false;}glBindFramebuffer(GL_FRAMEBUFFER,0);return true;}
bool Renderer::upload(const Mesh3&m){std::string why;if(!geo::validate(m,&why)){error_=why;return false;}std::vector<uint32_t>ix;ix.reserve(m.e.size()*2);for(auto e:m.e){ix.push_back(e.a);ix.push_back(e.b);}edgeCount_=(int)ix.size();glBindVertexArray(vao_);glBindBuffer(GL_ARRAY_BUFFER,vbo_);size_t vb=m.v.size()*sizeof(V3);if(vb>vboCapacity_){vboCapacity_=std::max(vb,vboCapacity_*2+4096);glBufferData(GL_ARRAY_BUFFER,vboCapacity_,nullptr,GL_DYNAMIC_DRAW);}if(vb)glBufferSubData(GL_ARRAY_BUFFER,0,vb,m.v.data());glVertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,sizeof(V3),nullptr);glEnableVertexAttribArray(0);glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,ebo_);size_t eb=ix.size()*sizeof(uint32_t);if(eb>eboCapacity_){eboCapacity_=std::max(eb,eboCapacity_*2+4096);glBufferData(GL_ELEMENT_ARRAY_BUFFER,eboCapacity_,nullptr,GL_DYNAMIC_DRAW);}if(eb)glBufferSubData(GL_ELEMENT_ARRAY_BUFFER,0,eb,ix.data());return true;}
bool Renderer::draw(float t,int width,int height,float aspect,float scale,float lineWidth,float musicLevel){if(!resizeHdr(width,height))return false;float ml=std::clamp(musicLevel,0.f,1.f);
 float fly=std::sin(t*.19f),zoom=std::sin(t*.23f+1.7f),breath=1.f+.075f*std::sin(t*.83f)+.12f*ml;
 float P[16],V[16]={1,0,0,0,0,1,0,0,0,0,1,0,.22f*fly,.14f*std::cos(t*.13f),-4.25f+.52f*zoom-.28f*ml,1};
 float Ry[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1},Rx[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1},R[16],X[16],M[16];
 float cy=std::cos(t*.17f),sy=std::sin(t*.17f),cx=std::cos(.27f*std::sin(t*.11f)),sx=std::sin(.27f*std::sin(t*.11f));
 Ry[0]=cy*scale*breath;Ry[2]=-sy*scale*breath;Ry[8]=sy*scale*breath;Ry[10]=cy*scale*breath;Ry[5]=scale*breath;
 Rx[5]=cx;Rx[6]=sx;Rx[9]=-sx;Rx[10]=cx;
 perspective(P,(52.f+3.f*std::sin(t*.07f)-2.f*ml)*3.14159265f/180.f,std::max(.05f,aspect),.05f,100.f);mul(R,Ry,Rx);mul(X,V,R);mul(M,P,X);glBindFramebuffer(GL_FRAMEBUFFER,hdrFbo_);glViewport(0,0,width,height);glClearColor(0,0,0,1);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glEnable(GL_DEPTH_TEST);glUseProgram(program_);glUniformMatrix4fv(uMVP_,1,GL_FALSE,M);glUniform1f(uTime_,t);if(uMusicLevel_>=0)glUniform1f(uMusicLevel_,ml);glUniform3f(uColor_,1.2f+.75f*ml,1.55f+.35f*ml,2.1f+1.1f*ml);glLineWidth(std::max(1.f,lineWidth+ml*.75f));glBindVertexArray(vao_);glDrawElements(GL_LINES,edgeCount_,GL_UNSIGNED_INT,nullptr);glBindFramebuffer(GL_FRAMEBUFFER,0);glDisable(GL_DEPTH_TEST);glUseProgram(postProgram_);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,hdrTex_);if(uPostTime_>=0)glUniform1f(uPostTime_,t);if(uPostResolution_>=0)glUniform2f(uPostResolution_,float(width),float(height));if(uPostMusic_>=0)glUniform1f(uPostMusic_,ml);glBindVertexArray(postVao_);glDrawArrays(GL_TRIANGLES,0,3);float overlayModelZoom=std::clamp(scale*breath*(1.f+.12f*zoom),.72f,1.45f);if(!drawOverlays(t,width,height,ml,overlayModelZoom))return false;return true;}
bool Renderer::drawOverlays(float t,int width,int height,float musicLevel,float modelZoom){
 if(!overlayProgram_||!logoTex_||!scrollerTex_)return true;
 auto quad=[&](GLuint tex,float cx,float cy,float w,float h,float alpha,float u0,float u1,float tintR,float tintG,float tintB,float fx){
  if(alpha<=0.f||w<=0.f||h<=0.f)return;
  float x0=cx-w*.5f,x1=cx+w*.5f,y0=cy-h*.5f,y1=cy+h*.5f;
  float v[]={x0,y0,u0,1.f,x1,y0,u1,1.f,x1,y1,u1,0.f,x0,y0,u0,1.f,x1,y1,u1,0.f,x0,y1,u0,0.f};
  glUseProgram(overlayProgram_);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,hdrTex_);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,tex);if(uOverlayAlpha_>=0)glUniform1f(uOverlayAlpha_,alpha);if(uOverlayTint_>=0)glUniform3f(uOverlayTint_,tintR,tintG,tintB);if(uOverlayTime_>=0)glUniform1f(uOverlayTime_,t);if(uOverlayFx_>=0)glUniform1f(uOverlayFx_,fx);
  glBindVertexArray(overlayVao_);glBindBuffer(GL_ARRAY_BUFFER,overlayVbo_);glBufferData(GL_ARRAY_BUFFER,sizeof(v),v,GL_STREAM_DRAW);glVertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,4*sizeof(float),nullptr);glEnableVertexAttribArray(0);glVertexAttribPointer(1,2,GL_FLOAT,GL_FALSE,4*sizeof(float),reinterpret_cast<void*>(2*sizeof(float)));glEnableVertexAttribArray(1);glDrawArrays(GL_TRIANGLES,0,6);
 };
 glDisable(GL_DEPTH_TEST);glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);
 float aspect=width>0&&height>0?float(width)/float(height):1.6f;
 // Smooth the decoded RMS before using it for scale: attack quickly on a hit,
 // release more slowly so the logo feels heavy instead of jittering.
 if(logoLastTime_<0.f||t<logoLastTime_||t-logoLastTime_>1.f) logoLastTime_=t;
 else {float dt=std::clamp(t-logoLastTime_,0.f,.08f);float target=std::clamp(musicLevel,0.f,1.f);float rate=target>logoLevel_?12.f:4.5f;logoLevel_+=(target-logoLevel_)*(1.f-std::exp(-rate*dt));logoLastTime_=t;}
 float travel=.5f+.5f*std::sin(t*.62f-1.1f); // 0 = receding into the wireframe, 1 = foreground hit
 float pulse=.84f+.28f*travel+.035f*std::sin(t*4.2f)+.22f*logoLevel_+.06f*logoLevel_*std::sin(t*9.1f);
 float logoFade=1.f-smoother(22.f,31.f,t);
 float intro=smoother(.15f,1.4f,t)*(1.f-.55f*smoother(10.f,18.f,t));
 float logoW=.94f*modelZoom;float logoH=logoW*(float(logoH_)/float(std::max(1,logoW_)))*aspect;float logoY=.49f+.035f*std::sin(t*.62f-1.1f);quad(logoTex_,0.f,logoY,logoW*pulse,logoH*pulse,std::min(1.f,intro+.22f)*logoFade,0.f,1.f,1.12f,1.04f,1.f,.92f+.08f*logoLevel_);
 float greetsW=.86f;float greetsH=greetsW*(float(greetsH_)/float(std::max(1,greetsW_)))*aspect;
 // Cross-fade the supplied red greets card with the blue/orange Mega OpenGL card.
 // The slow cycle keeps both marks readable while making the branding part of the show.
 float brandMix=.5f+.5f*std::sin(t*.12f);float greetsAlpha=.72f*smoother(4.5f,7.2f,t)*(1.f-.72f*brandMix);quad(greetsTex_,0.f,-.18f,greetsW,greetsH,greetsAlpha,0.f,1.f,1.05f,.99f,.96f,.55f+.2f*musicLevel);
 if(accentTex_&&accentW_>0&&accentH_>0){float accentW=.86f;float accentH=accentW*(float(accentH_)/float(std::max(1,accentW_)))*aspect;float accentAlpha=.62f*smoother(4.5f,7.2f,t)*(.18f+.82f*brandMix);quad(accentTex_,0.f,-.18f,accentW,accentH,accentAlpha,0.f,1.f,1.f,1.f,1.f,.65f);}
 if(scrollerW_>0&&scrollerH_>0){
  // Advance an accumulator instead of deriving the UV directly from the clock:
  // short audio/timeline corrections no longer make the text jump.
  float speed=.0038f+.0007f*musicLevel;
  if(overlayLastTime_<0.f||t<overlayLastTime_||t-overlayLastTime_>1.f) overlayLastTime_=t;
  else {overlayScrollU_=std::fmod(overlayScrollU_+(t-overlayLastTime_)*speed,1.f);overlayLastTime_=t;}
  if(overlayScrollU_<0.f)overlayScrollU_+=1.f;
  float visible=.62f;float uSpan=std::min(1.f,visible*float(scrollerH_)/float(scrollerW_)*aspect*2.8f);float u0=overlayScrollU_;float u1=u0+uSpan;float y=-.84f+.006f*std::sin(t*1.7f);quad(scrollerTex_,0.f,y,1.98f,.24f,1.f,u0,u1,1.18f,1.05f,1.f,1.f);
 }
 glDisable(GL_BLEND);return true;
}
void Renderer::shutdown(){if(logoTex_)glDeleteTextures(1,&logoTex_);if(greetsTex_)glDeleteTextures(1,&greetsTex_);if(accentTex_)glDeleteTextures(1,&accentTex_);if(scrollerTex_)glDeleteTextures(1,&scrollerTex_);if(overlayVbo_)glDeleteBuffers(1,&overlayVbo_);if(overlayVao_)glDeleteVertexArrays(1,&overlayVao_);if(overlayProgram_)glDeleteProgram(overlayProgram_);if(hdrFbo_)glDeleteFramebuffers(1,&hdrFbo_);if(hdrTex_)glDeleteTextures(1,&hdrTex_);if(depthRbo_)glDeleteRenderbuffers(1,&depthRbo_);if(postProgram_)glDeleteProgram(postProgram_);if(postVao_)glDeleteVertexArrays(1,&postVao_);if(program_)glDeleteProgram(program_);if(ebo_)glDeleteBuffers(1,&ebo_);if(vbo_)glDeleteBuffers(1,&vbo_);if(vao_)glDeleteVertexArrays(1,&vao_);program_=postProgram_=overlayProgram_=vao_=postVao_=overlayVao_=vbo_=ebo_=overlayVbo_=hdrFbo_=hdrTex_=depthRbo_=logoTex_=greetsTex_=accentTex_=scrollerTex_=0;}
